# see `man dnf.conf` for defaults and possible options
# /etc/dnf/dnf.conf

[main]
max_parallel_downloads=10
fastestmirror=True
minrate=1k
timeout=30
installonly_limit=2
gpgcheck=True
clean_requirements_on_remove=True
